---
###############################################################################
# Crashplan for Business
###############################################################################
# Instuctions for connecting to and adopting a new installation to an existing
# dataset.
#
# Reference:
# * https://github.com/jlesage/docker-crashplan-pro#taking-over-existing-backup

- name: 'ACTION REQUIRED'
  ansible.builtin.debug:
    msg: |
      Connect remotely to GUI for backup adoption:

        Windows
        -------
        xlaunch:
          * multiple windows
          * display windows: -1
          * start no client
          * clipboard (checked), primary selection (checked)
          * native opengl (checked)

        putty:
        connection -> ssh -> x11
          * enable x11 forwarding (checked)
          * x display location: localhost:0.0
          * MIT-Magic-Cookie-1 (checked)

        Linux
        -----
        ssh: no configuration required. Just xserver running.


      Run GUI:

        ssh -X {USER}@{{ inventory_hostname }}
        /usr/local/crashplan/bin/desktop.sh

      Backup set Adoption:

        * Start container.
        * Sign in to your account.
        * Click the Replace Existing button to start the wizard.
        * **SKIP** File Transfer.
        * Once done with the wizard, go to your device's details and click Manage
          Files. You will probably see missing items in the file selection. This
          is normal, since path to your files may be different in the container.
        * Update the file selection by re-adding your files. Do not unselect
          missing items yet.
        * Perform a backup. Because of deduplication, files will not be uploaded
          again.
        * Once the backup is terminated, you can remove missing items if you
          don't care about file versions. Else, keep missing items.

        https://support.code42.com/CrashPlan/6/Configuring/Replace_your_device
